In [1]:
import numpy as np
from sympy import *

init_printing()

In [2]:
def get_length(v):
    length = 0
    for i in v:
        length += i ** 2
    return np.sqrt(length)

In [3]:
def get_unit_vector(v):
    return v / get_length(v)

In [60]:
def gram_schmidt(b):
    orthonormal_basis = []
    for i in b:
        temp = i
        for j in range(0, len(orthonormal_basis)):
            temp = temp - np.dot(np.dot(temp, orthonormal_basis[j]), orthonormal_basis[j])
        print(temp)
        orthonormal_basis.append(get_unit_vector(temp))
    return np.array(orthonormal_basis)

In [44]:
gram_schmidt(np.array([[0,0,1,1],[0,1,1,0],[1,1,0,0]]))

array([[ 0.        ,  0.        ,  0.70710678,  0.70710678],
       [ 0.        ,  0.81649658,  0.40824829, -0.40824829],
       [ 0.8660254 ,  0.28867513, -0.28867513,  0.28867513]])

In [45]:
gram_schmidt(np.array([[1,1,1,1],[-2,0,1,3], [-4,-3,3,0]]))

array([[ 0.5       ,  0.5       ,  0.5       ,  0.5       ],
       [-0.69337525, -0.13867505,  0.13867505,  0.69337525],
       [-0.12126781, -0.36380344,  0.84887469, -0.36380344]])

In [52]:
gram_schmidt(np.array([[-1,-1,-2,0],[-3.5,-1.5,-2,1],[-6,11,-5.5,-3.5]]))

array([[-4.08248290e-01, -4.08248290e-01, -8.16496581e-01,
         0.00000000e+00],
       [-8.16496581e-01,  9.06493304e-17,  4.08248290e-01,
         4.08248290e-01],
       [-2.88675135e-01,  8.66025404e-01, -2.88675135e-01,
        -2.88675135e-01]])

In [54]:
gram_schmidt([[1,0,0],[2,0,3],[4,5,6]])

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [55]:
gram_schmidt([[1,1,0],[1,0,1],[0,1,1]])

array([[ 0.70710678,  0.70710678,  0.        ],
       [ 0.40824829, -0.40824829,  0.81649658],
       [-0.57735027,  0.57735027,  0.57735027]])

In [59]:
q1 = np.array([ 0.5       ,  0.5       ,  0.5       ,  0.5       ])
q2 = np.array([-0.69337525, -0.13867505,  0.13867505,  0.69337525])

b = np.array([-4,-3,3,0])

p1 = np.dot(np.dot(b, q1), q1)
p2 = np.dot(np.dot(b, q2), q2)
p1+p2

array([-3.50000003, -1.50000001, -0.49999999,  1.50000003])

In [61]:
gram_schmidt([[1,-1,0,0],[0,1,-1,0],[0,0,1,-1]])

[1, -1, 0, 0]
[ 0.5  0.5 -1.   0. ]
[ 0.33333333  0.33333333  0.33333333 -1.        ]


array([[ 0.70710678, -0.70710678,  0.        ,  0.        ],
       [ 0.40824829,  0.40824829, -0.81649658,  0.        ],
       [ 0.28867513,  0.28867513,  0.28867513, -0.8660254 ]])